# Generated by Django 5.0.14 on 2026-08-23 11:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('EXAM', 'Examination'), ('CIRCULAR', 'Official Circular'), ('ADMISSION', 'Admissions'), ('EVENT', 'News & Event'), ('GENERAL', 'General Notice')], default='GENERAL', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='announcements/')),
                ('link', models.URLField(blank=True, null=True)),
                ('is_important', models.BooleanField(default=False)),
                ('is_ticker', models.BooleanField(default=True, help_text='Show in running notification ticker')),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampusFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fa-building', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='committees/')),
                ('external_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_class', models.CharField(default='fa-laptop-code', help_text='FontAwesome icon class e.g. fa-laptop-code, fa-cogs, fa-bolt, fa-drafting-compass, fa-microchip', max_length=50)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('intake', models.PositiveIntegerField(default=60)),
                ('duration', models.CharField(default='3 Years (6 Semesters)', max_length=50)),
                ('hod_name', models.CharField(blank=True, max_length=100)),
                ('hod_qualification', models.CharField(blank=True, max_length=100)),
                ('hod_message', models.TextField(blank=True)),
                ('lab_facilities', models.TextField(blank=True, help_text='Bullet points or newline separated list of labs')),
                ('image', models.ImageField(blank=True, null=True, upload_to='departments/')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('CAMPUS', 'Campus Infrastructure'), ('LABS', 'Laboratories & Workshops'), ('EVENTS', 'Events & Celebrations'), ('SPORTS', 'Sports & Cultural'), ('ACADEMICS', 'Academic Activities')], default='CAMPUS', max_length=20)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Topper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('semester', models.CharField(help_text='e.g. 1st Sem, 3rd Sem, 5th Sem', max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.CharField(default='2024-2025', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='toppers/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppers', to='website.department')),
            ],
            options={
                'ordering': ['-percentage'],
            },
        ),
    ]
