# Generated by Django 5.0.14 on 2026-08-23 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(help_text='e.g. Head of Department, Senior Lecturer, Selection Grade Lecturer', max_length=100)),
                ('qualification', models.CharField(help_text='e.g. M.Tech, B.E., Ph.D.', max_length=150)),
                ('experience', models.CharField(blank=True, help_text='e.g. 10+ Years', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty/')),
                ('is_hod', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='website.department')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
