# Generated by Django 5.0.14 on 2026-08-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_facultymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title, e.g. Grievance Redressal Committee Report', max_length=200)),
                ('category', models.CharField(default='AICTE & DTE Document', help_text='Category badge or brief tag', max_length=100)),
                ('file', models.FileField(blank=True, help_text='Upload PDF or document file', null=True, upload_to='downloads/')),
                ('external_link', models.URLField(blank=True, help_text='Or enter an external link if no file is uploaded', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display priority order')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
