# Generated by Django 5.0.14 on 2026-08-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_quickdownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('FOUNDER', 'Founder / Poojyasri Desk'), ('PRINCIPAL', 'Principal Desk'), ('PRESIDENT', 'President / Management Desk'), ('SECRETARY', 'Secretary Desk')], default='FOUNDER', max_length=20, unique=True)),
                ('honorific', models.CharField(blank=True, default='Poojyasri', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='e.g. Ex. M.L.C | Founder, Madhugiri Education Society (R)', max_length=150)),
                ('message', models.TextField(help_text='Vision quote or message to students')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'role_type'],
            },
        ),
    ]
